#!/bin/bash

cd "$(dirname $0)"

if [[ -z "$(which docker)" ]]; then
	echo "Please install Docker from https://www.docker.com"

	exit 1
fi

cmd="docker run --rm -v "$(pwd):/opt/wappalyzer" -it wappalyzer/dev"

$cmd sh -c "yarn install; cd src/drivers/webextension; yarn install"

$cmd ./bin/run links
$cmd ./bin/run $@
