name: "submit"
on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Download Github Release Assets
        uses: PlasmoHQ/download-release-asset@v1.0.0
        with:
          files: webextension.zip
      - name: Browser Plugin Publish
        uses: PlasmoHQ/bpp@v2
        with:
          artifact: webextension.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
